namespace AuthenCard.Models 
{
    public class Patient 
    {
        public string hosGuid { get; set; }
        public string hn { get; set; }
        public string pname { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string occupation { get; set; }
        public string citizenship { get; set; }
        public string birthday { get; set; }
        public string addrpart { get; set; }
        public string moopart { get; set; }
        public string tmbpart { get; set; }
        public string amppart { get; set; }
        public string chwpart { get; set; }
        public string bloodgrp { get; set; }
        public string clinic { get; set; }
        public object deathday { get; set; }
        public string drugallergy { get; set; }
        public object familyno { get; set; }
        public string fathername { get; set; }
        public string firstday { get; set; }
        public string hometel { get; set; }
        public string informaddr { get; set; }
        public string informname { get; set; }
        public string informrelation { get; set; }
        public string informtel { get; set; }
        public string marrystatus { get; set; }
        public string mathername { get; set; }
        public int hnInt { get; set; }
        public string nationality { get; set; }
        public object opdlocation { get; set; }
        public string pttype { get; set; }
        public string religion { get; set; }
        public string sex { get; set; }
        public string spsname { get; set; }
        public string truebirthday { get; set; }
        public object workaddr { get; set; }
        public object worktel { get; set; }
        public string hcode { get; set; }
        public string cid { get; set; }
        public int hid { get; set; }
        public object educate { get; set; }
        public object familyStatus { get; set; }
        public object laborType { get; set; }
        public DateTime lastUpdate { get; set; }
        public object typeArea { get; set; }
        public string road { get; set; }
        public string fatherCid { get; set; }
        public string motherCid { get; set; }
        public string coupleCid { get; set; }
        public object personType { get; set; }
        public string privateDoctorName { get; set; }
        public string legalAction { get; set; }
        public object deathCode504 { get; set; }
        public object deathDiag { get; set; }
        public string nodeId { get; set; }
        public string admit { get; set; }
        public string midname { get; set; }
        public string poCode { get; set; }
        public string fatherlname { get; set; }
        public string motherlname { get; set; }
        public string spslname { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string birthtime { get; set; }
        public string motherHn { get; set; }
        public string lastVisit { get; set; }
        public string death { get; set; }
        public int height { get; set; }
        public string inregion { get; set; }
        public string regTime { get; set; }
        public string oldcode { get; set; }
        public string lang { get; set; }
        public string govChronicId { get; set; }
        public string inCups { get; set; }
        public object patientTypeId { get; set; }
        public object addrSoi { get; set; }
        public string workAddr1 { get; set; }
        public object fatherHn { get; set; }
        public string aliasName { get; set; }
        public object destroyed { get; set; }
        public object oldAddr { get; set; }
        public string fnameSoundex { get; set; }
        public string lnameSoundex { get; set; }
        public string bloodgroupRh { get; set; }
        public string tranStatus { get; set; }
        public string passportNo { get; set; }
        public object addressid { get; set; }
        public object mobilePhoneNumber { get; set; }
        public object anonymousPerson { get; set; }
        public object hospitalDepartmentId { get; set; }
        public object membercardNo { get; set; }
        public object ecFname { get; set; }
        public object ecLname { get; set; }
        public object ecRelationTypeId { get; set; }
        public object patientColorId { get; set; }
        public object numberOfRelatives { get; set; }
        public object birthOrder { get; set; }
        public object personLaborTypeId { get; set; }
        public object isCardDestroy { get; set; }
        public object cardDestroyDate { get; set; }
        public object g6pd { get; set; }
        public object vid { get; set; }
    }

}